---
title: "Themed Dashboard"
format: 
    dashboard:
        theme: lux
        vertical_layout: fill
---

```{r setup}
#| include: false

library(palmerpenguins)
library(ggplot2)
library(dplyr)
library(leaflet) # interactive maps
library(plotly) # interactive plots
library(knitr)
```

```{r}
# save data to object
penguin_df <- palmerpenguins::penguins
```

## Row 1 {height=20%}


### Chart A

```{r}
#| content: valuebox
#| title: "Total Penguins"

list(
  icon = "hash",
  color = "warning",
  value = nrow(penguins)
)
```

### Chart B

```{r}
#| content: valuebox
#| title: "Mean Body Mass (kg)"

mean_mass <- mean(penguins$body_mass_g, na.rm = TRUE)/1000

list(
  icon = "feather",
  color = "light",
  value = mean_mass)
```


## Row 2 {height=80%}


### Column 1 {.tabset}

```{r}
#| title: Bill Depth Distribution of Chinstrap

penguins %>%
    filter(species == "Chinstrap") %>%
    ggplot(aes(x = bill_depth_mm)) +
    geom_histogram(fill = "orange") +
    labs(title = NULL,
         x = "Bill Depth (mm)",
         y = NULL) +
    theme_minimal()
```

```{r}
#| title: Penguin Species Summary

penguin_species <- penguins %>% 
    group_by(species) %>% 
    summarise(count = n())
    
kable(penguin_species)
```


### Column 2

```{r}
#| title: Interactive Scatterplot

scatterplot <- ggplot(data = penguins, aes(x = flipper_length_mm, y = body_mass_g)) +
    geom_point(aes(color = species)) +
    scale_color_manual(values = c(
        "Adelie" = "purple2",
        "Chinstrap" = "orange",
        "Gentoo" = "cyan4"
    )) +
    labs(
        title = NULL,
        x = "Flipper Length (mm)",
        y = "Body Mass (g)",
        color = "Species"
    ) +
    theme_minimal()

ggplotly(scatterplot)
```



